import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import PasswordField from '../components/password-field/password-field'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Is It Valid?</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <div>Insecure Password</div>
          <PasswordField validationRuleSetName='insecure-password' />
        </div>
        <div>
          <div>Okay Password</div>
          <PasswordField validationRuleSetName='okay-password' />
        </div>
        <div>
          <div>Secure Password</div>
          <PasswordField validationRuleSetName='secure-password' />
        </div>
      </main>
    </>
  )
}
